name 'dsc_core'
maintainer 'Stuart Preston'
maintainer_email 'stuart@pendrica.com'
license 'all_rights'
description 'Installs/Configures dsc_core'
long_description 'Installs/Configures dsc_core'
version '0.1.0'
